# Generated by Django 4.2.1 on 2023-05-06 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
