# Generated by Django 4.2.1 on 2023-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_student_datetime1_student_number_of_bikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='datetime1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='number_of_bikes',
        ),
    ]
