# Generated by Django 4.2.1 on 2023-05-06 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_cars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='name',
            new_name='car_name',
        ),
    ]
